Fix for null pointer because component is already removed from the parent.
ERROR org.sablo.eventthread.Event - Exception in after execute
java.lang.NullPointerException: Cannot invoke
"org.sablo.Container.getName()" because "topContainer" is null

at org.sablo.websocket.BaseWindow$ComponentCall.writeToJSON(BaseWindow.java:1175)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.websocket.BaseWindow.sendMessageInternal(BaseWindow.java:563)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.websocket.BaseWindow.sendAsyncMessage(BaseWindow.java:504)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.websocket.BaseWindow.sendChanges(BaseWindow.java:706)
~[sablo_2023.3.2.3844.jar:?]

at com.servoy.j2db.server.ngclient.NGClientWindow.sendChanges(NGClientWindow.java:125)
~[?:?]

at org.sablo.eventthread.WebsocketSessionWindows.sendChanges(WebsocketSessionWindows.java:247)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.websocket.BaseWebsocketSession.valueChanged(BaseWebsocketSession.java:487)
~[sablo_2023.3.2.3844.jar:?]

at com.servoy.j2db.server.ngclient.NGClientWebsocketSession.valueChanged(NGClientWebsocketSession.java:456)
~[?:?]

at org.sablo.websocket.BaseWebsocketSession.stopHandlingEvent(BaseWebsocketSession.java:475)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.Event.afterExecute(Event.java:137)
~[sablo_2023.3.2.3844.jar:?]

at com.servoy.j2db.server.ngclient.eventthread.NGEvent.afterExecute(NGEvent.java:70)
~[?:?]

at org.sablo.eventthread.Event$1.run(Event.java:115)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.Event.execute(Event.java:87)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:135)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.EventDispatcher.suspend(EventDispatcher.java:272)
~[sablo_2023.3.2.3844.jar:?]

at com.servoy.j2db.server.ngclient.NGRuntimeWindow.doOldShow(NGRuntimeWindow.java:551)
~[?:?]

at com.servoy.j2db.scripting.RuntimeWindow.doShow(RuntimeWindow.java:304)
~[servoy_shared_2023.3.2.3844.jar:?]

at com.servoy.j2db.scripting.RuntimeWindow.show(RuntimeWindow.java:298)
~[servoy_shared_2023.3.2.3844.jar:?]

at com.servoy.j2db.scripting.RuntimeWindow.showObject(RuntimeWindow.java:285)
~[servoy_shared_2023.3.2.3844.jar:?]

at com.servoy.j2db.scripting.JSWindow.js_show(JSWindow.java:155)
~[servoy_shared_2023.3.2.3844.jar:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~[?:?]

at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
~[?:?]

at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown
Source) ~[?:?]

at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]

at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:220)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:284)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1053)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3944)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:88)
~[org.eclipse.dltk.javascript.rhino_1.7.14.s3.jar:?]

at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:718)
~[servoy_shared_2023.3.2.3844.jar:?]

at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393)
~[?:?]

at com.servoy.j2db.server.ngclient.component.EventExecutor.executeEvent(EventExecutor.java:207)
~[?:?]

at com.servoy.j2db.server.ngclient.DataAdapterList.executeEvent(DataAdapterList.java:198)
~[?:?]

at com.servoy.j2db.server.ngclient.WebFormComponent$FormcomponentEventHandler.executeEvent(WebFormComponent.java:251)
~[?:?]

at org.sablo.BaseWebObject.doExecuteEvent(BaseWebObject.java:372)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.BaseWebObject.executeEvent(BaseWebObject.java:334)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.services.server.FormServiceHandler.executeEvent(FormServiceHandler.java:132)
~[sablo_2023.3.2.3844.jar:?]

at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeEvent(NGFormServiceHandler.java:617)
~[?:?]

at org.sablo.services.server.FormServiceHandler.executeMethod(FormServiceHandler.java:83)
~[sablo_2023.3.2.3844.jar:?]

at com.servoy.j2db.server.ngclient.NGFormServiceHandler.executeMethod(NGFormServiceHandler.java:596)
~[?:?]

at org.sablo.websocket.WebsocketEndpoint$5.run(WebsocketEndpoint.java:410)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.Event$1.run(Event.java:97)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:80)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.Event.execute(Event.java:87)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:135)
~[sablo_2023.3.2.3844.jar:?]

at org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java:90)
~[sablo_2023.3.2.3844.jar:?]

at com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java:60)
~[?:?]

at java.lang.Thread.run(Unknown Source) ~[?:?]